#!/bin/zsh

#EFFECT=(-depth 2 -scale 10% -scale 1000%)
#EFFECT=(-depth 2 -filter Point -resize '5%' -resize '2000%')
EFFECT=()
#FILE=(~/.config/i3/lock)
DIR=$(mktemp -d)
FILE="$DIR/file"
DATE=$(date +"%y-%m-%d-%H-%M-%S")
RESOLUTION=$(xdpyinfo | grep 'dimensions:' | awk '{print substr($2, 1)}')

ffmpeg -y -loglevel 0 -t 1 -s $RESOLUTION -f x11grab -i $DISPLAY $FILE.bmp ||
cd ~/.config/i3/ &&
./screenshotmangler $FILE.bmp $FILE.bmp &&
convert $FILE.bmp ${EFFECT[@]} -define PNG:compression-level=0 -define PNG:compression-strategy=0 -define PNG:compression-filter=3 $FILE.png &&
i3lock -u -p win -i $FILE.png &
convert $FILE.bmp ${EFFECT[@]} -define PNG:compression-level=9 -define PNG:compression-strategy=2 -define PNG:compression-filter=2 $DATE.png &&
mv $DATE.png ~/pictures/lockscreens/$DATE.png &&
rm -r $DIR
