(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-clean-confirm nil)
 '(ansi-color-names-vector
   ["#282828" "#fb4934" "#b8bb26" "#fabd2f" "#83a598" "#cc241d" "#8ec07c" "#ebdbb2"])
 '(custom-safe-themes
   '("2b3f1e6abe0f02ff73d95dca04901bdbc2ecebe80fa453eded34fa39c8b050cb" "835868dcd17131ba8b9619d14c67c127aa18b90a82438c8613586331129dda63" "7eea50883f10e5c6ad6f81e153c640b3a288cd8dc1d26e4696f7d40f754cc703" default))
 '(evil-move-beyond-eol t)
 '(evil-snipe-scope 'visible)
 '(exwm-floating-border-color "#504945")
 '(fci-rule-color "#7c6f64")
 '(geiser-active-implementations '(chez) t)
 '(geiser-chez-binary "chezscheme")
 '(highlight-tail-colors ((("#363627" "#363627") . 0) (("#323730" "#323730") . 20)))
 '(httpd-port 8070)
 '(jdee-db-active-breakpoint-face-colors (cons "#0d1011" "#fabd2f"))
 '(jdee-db-requested-breakpoint-face-colors (cons "#0d1011" "#b8bb26"))
 '(jdee-db-spec-breakpoint-face-colors (cons "#0d1011" "#928374"))
 '(js-indent-level 2)
 '(lsp-file-watch-threshold nil)
 '(magit-gitflow-hotfix-finish-arguments '("--notag"))
 '(magit-gitflow-release-finish-arguments '("--notag"))
 '(magit-todos-insert-after '(bottom) nil nil "Changed by setter of obsolete option `magit-todos-insert-at'")
 '(midnight-mode t)
 '(objed-cursor-color "#fb4934")
 '(org-log-done 'time)
 '(pdf-view-midnight-colors (cons "#ebdbb2" "#282828"))
 '(python-pytest-executable "venv/bin/pytest")
 '(python-shell-interpreter "ipython")
 '(python-shell-interpreter-args "--simple-prompt")
 '(require-final-newline nil)
 '(rustic-ansi-faces
   ["#282828" "#fb4934" "#b8bb26" "#fabd2f" "#83a598" "#cc241d" "#8ec07c" "#ebdbb2"])
 '(safe-local-variable-values '((checkdoc-package-keywords-flag)))
 '(scheme-program-name "chezscheme")
 '(smerge-command-prefix "SPC g m")
 '(tab-width 4)
 '(tree-sitter-major-mode-language-alist
   '((agda2-mode . agda)
     (sh-mode . bash)
     (c-mode . c)
     (caml-mode . ocaml)
     (clojure-mode . clojure)
     (csharp-mode . c-sharp)
     (c++-mode . cpp)
     (d-mode . d)
     (css-mode . css)
     (elm-mode . elm)
     (elixir-mode . elixir)
     (erlang-mode . erlang)
     (ess-r-mode . r)
     (fennel-mode . fennel)
     (go-mode . go)
     (haskell-mode . haskell)
     (hcl-mode . hcl)
     (terraform-mode . hcl)
     (html-mode . html)
     (markdown-mode . markdown)
     (mhtml-mode . html)
     (nix-mode . nix)
     (java-mode . java)
     (javascript-mode . javascript)
     (js-mode . javascript)
     (js2-mode . javascript)
     (js3-mode . javascript)
     (json-mode . json)
     (jsonc-mode . json)
     (julia-mode . julia)
     (lua-mode . lua)
     (matlab-mode . matlab)
     (meson-mode . meson)
     (ocaml-mode . ocaml)
     (perl-mode . perl)
     (php-mode . php)
     (prisma-mode . prisma)
     (python-mode . python)
     (pygn-mode . pgn)
     (rjsx-mode . javascript)
     (ruby-mode . ruby)
     (rust-mode . rust)
     (rustic-mode . rust)
     (scala-mode . scala)
     (scheme-mode . scheme)
     (svelte-mode . svelte)
     (swift-mode . swift)
     (toml-mode . toml)
     (tuareg-mode . ocaml)
     (typescript-mode . typescript)
     (verilog-mode . verilog)
     (yaml-mode . yaml)
     (zig-mode . zig)))
 '(vc-annotate-background "#282828")
 '(vc-annotate-color-map
   (list
    (cons 20 "#b8bb26")
    (cons 40 "#cebb29")
    (cons 60 "#e3bc2c")
    (cons 80 "#fabd2f")
    (cons 100 "#fba827")
    (cons 120 "#fc9420")
    (cons 140 "#fe8019")
    (cons 160 "#ed611a")
    (cons 180 "#dc421b")
    (cons 200 "#cc241d")
    (cons 220 "#db3024")
    (cons 240 "#eb3c2c")
    (cons 260 "#fb4934")
    (cons 280 "#e05744")
    (cons 300 "#c66554")
    (cons 320 "#ac7464")
    (cons 340 "#7c6f64")
    (cons 360 "#7c6f64")))
 '(vc-annotate-very-old-color nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ts-fold-replacement-face ((t (:foreground unspecified :box nil :inherit font-lock-comment-face :weight light)))))
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 
