add_newline = false

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "⏱ [$duration]($style) "
show_notifications = true
min_time_to_notify = 60_000

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 2

[line_break]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
truncation_length = 4
truncation_symbol = "…"

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\(${virtualenv}\\) )]($style)"